SELECT YEAR, MONTH*1, GENDER, COUNT(USERS) AS USERS FROM (SELECT      
    DISTINCT
            TO_CHAR(B.SALES_DATE, 'YYYY')   YEAR
        ,   TO_CHAR(B.SALES_DATE, 'MM')     MONTH
        ,   A.GENDER GENDER
        ,   A.USER_ID USERS
        FROM        USER_INFO A JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
        WHERE       1=1
            AND A.USER_ID = B.USER_ID
            AND A.GENDER IS NOT NULL) GROUP BY YEAR, MONTH, GENDER ORDER BY YEAR, MONTH, GENDER